### ISSUE TITLE
Support for running benchmark simultaneously on different devices

### ISSUE THREAD

**Issue by TheKK** [dminor/mozbench#18]
For now, mozbench should runs benchmark one after one and one device after the other device if we want to run benchmarks on multiple devices. We can do this better by sending commands parallel to devices and save more time.

My rough idea is to open more servers with different ports for each device and request handler to correctly collect and generate benchmark results.

I'll write some dirty codes to check if this could work :)

**Comment by TheKK** [comment]
TheKK/mozbench@37bb2db60d072fdbf30f8602c2e5926d178b811f
My current solution is creating http server with random port number, and examining if this port was used. I also write a simple script to run mozbench on desktop, B2G and android parallel and it works great!

If there's something could be improved, just let me know.

**Comment by dminor** [comment]
I'm fine with using a random port number as long as we have a way to run it on a predetermined port as well. Maybe add a --use-randomized-port option that causes this code to be run when it is specified?

**Comment by TheKK** [comment]
@dminor: You're right, it's better idea to let user specify which port number to use rather than randomize it in mozbench. I've created #22 for this feature and some minor enhancement.
