### ISSUE TITLE
Add general output format for benchmark results

### ISSUE THREAD

**Issue by TheKK** [dminor/mozbench#23]
Currently, there's no way to generate any general output format, so I add an option, --json-result, to create developer-friendly JSON data. Here's the result after running `python mozbench.py --log-mach - --firefox-url fennec.apk --run-android-browser` with 2 benchmark suites:
https://gist.github.com/anonymous/02484c8df8bc545fab4b

I think we could discuss the final form and data contained of this output, or even should this feature exist or not.

**Comment by dminor** [comment]
This sounds like a good feature to me. We could just dump out data in the format that Influxdb accepts (the "results_to_post" variable) but that format isn't as easy to work with as what you suggest.

**Comment by TheKK** [comment]
dirty_code@47035355618881b55474d6d5141eb4861a9a54f3
I add this feature to Mozbench but codes get really mess. I'll find a way to make everything clear like wrap result storing as classes or functions.

Any suggestion or idea?

**Comment by dminor** [comment]
I wonder if you could change formatresults to store things in the format you suggested and then change postresults to switch from your format to the one I use for InfluxDB? Or is that what you tried already?
